### PR TITLE
plot raw Mfield

### PR DESCRIPTION
**Pull request by ajnonaka**
add raw M field output to plotfile if <diag_name>.plot_raw_fields=1
M_xface (note: each contains all 3 components)
M_yface
M_zface

### CODE REVIEW

**Comment by RevathiJambunathan** [comment]
@ajnonaka Thank you so much for this PR!!!  Please can you add the input file here that was used to test this with evolveM_dev, so that anyone interested in using this option, knows how to add it.

Also, for the cell-centered data we have `Mx_xface` and for the raw-data, we have `M_xface`. This is due to the staggering. Please can you add a description about this, highlighting what each would do, briefly, in the documentation. 

Docs/source/running_cpp/parameters.rst
Below <diag_name>.fields_to_plot for the cell-centered diags to list the options that we currently have.
And below <diag_name>.plot_raw_fields
 to list the options that we have for M_fields mentioning that the two are different due to the staggering. Also, please add a note there stating that these diags can only be output if the code is compiled with `USE_LLG=TRUE`.

**Comment by ajnonaka** [comment]
Here is an inputs file that can be used to test the functionality:

################################
####### GENERAL PARAMETERS ######
#################################
max_step = 0
plot_int = 10
amr.n_cell = 128 128 128
amr.max_grid_size = 32
amr.blocking_factor = 32
geometry.coord_sys   = 0
geometry.is_periodic = 1  1  1
geometry.prob_lo     =  -32.e-6 -32.e-6 -32.e-6
geometry.prob_hi     =   32.e-6  32.e-6  32.e-6
amr.max_level = 0

#################################
############ NUMERICS ###########
#################################
warpx.verbose = 0
warpx.use_filter = 0
warpx.cfl = 1.
warpx.do_pml = 0

#algo.em_solver_medium = vacuum # vacuum/macroscopic
#algo.macroscopic_sigma_method = backwardeuler # laxwendroff or backwardeuler
#macroscopic.sigma = 0.0
#macroscopic.epsilon = 8.8541878128e-12
#macroscopic.mu = 1.25663706212e-06

particles.nspecies = 0

#################################
############ FIELDS #############
#################################

my_constants.pi = 3.14159265359
my_constants.L = 141.4213562373095e-6
my_constants.c = 299792458.
my_constants.wavelength = 64.e-6

warpx.E_ext_grid_init_style = parse_E_ext_grid_function
warpx.Ez_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Ex_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Ey_external_grid_function(x,y,z) = "x*x+y*y+z*z"

warpx.B_ext_grid_init_style = parse_B_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.By_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Bz_external_grid_function(x,y,z) = "x*x+y*y+z*z"

warpx.M_ext_grid_init_style = constant
warpx.M_external_grid = 1. 2. 3.

# Diagnostics
diagnostics.diags_names = diag1
diag1.period = 100
diag1.diag_type = Full

diag1.fields_to_plot = Ex Ey Ez Bx By Bz Mx_xface Mx_yface Mx_zface My_xface My_yface My_zface Mz_xface Mz_yface Mz_zface

diag1.plot_raw_fields = 1

**Comment by ajnonaka** [comment]
Here is an inputs file for testing:

################################
####### GENERAL PARAMETERS ######
#################################
max_step = 0
plot_int = 1
amr.n_cell = 128 128 128
amr.max_grid_size = 32
amr.blocking_factor = 32
geometry.coord_sys   = 0
geometry.is_periodic = 1  1  1
geometry.prob_lo     =  -32.e-6 -32.e-6 -32.e-6
geometry.prob_hi     =   32.e-6  32.e-6  32.e-6
amr.max_level = 0

#################################
############ NUMERICS ###########
#################################
warpx.verbose = 0
warpx.use_filter = 0
warpx.cfl = 1.
warpx.do_pml = 0

#algo.em_solver_medium = vacuum # vacuum/macroscopic
#algo.macroscopic_sigma_method = backwardeuler # laxwendroff or backwardeuler
#macroscopic.sigma = 0.0
#macroscopic.epsilon = 8.8541878128e-12
#macroscopic.mu = 1.25663706212e-06

particles.nspecies = 0

#################################
############ FIELDS #############
#################################

my_constants.pi = 3.14159265359
my_constants.L = 141.4213562373095e-6
my_constants.c = 299792458.
my_constants.wavelength = 64.e-6

warpx.E_ext_grid_init_style = parse_E_ext_grid_function
warpx.Ez_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Ex_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Ey_external_grid_function(x,y,z) = "x*x+y*y+z*z"

warpx.B_ext_grid_init_style = parse_B_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.By_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Bz_external_grid_function(x,y,z) = "x*x+y*y+z*z"

warpx.M_ext_grid_init_style = constant
warpx.M_external_grid = 1. 2. 3.

#################################
############ DIAGNOSTICS #############
#################################

diagnostics.diags_names = diag1
diag1.period = 100
diag1.diag_type = Full

diag1.fields_to_plot = Ex Ey Ez Bx By Bz Mx_xface Mx_yface Mx_zface My_xface My_yface My_zface Mz_xface Mz_yface Mz_zface

diag1.plot_raw_fields = 1

**Comment by ajnonaka** [comment]
Here is an inputs file that can be used for testing:

`
################################
####### GENERAL PARAMETERS ######
#################################
max_step = 0
plot_int = 1
amr.n_cell = 128 128 128
amr.max_grid_size = 32
amr.blocking_factor = 32
geometry.coord_sys   = 0
geometry.is_periodic = 1  1  1
geometry.prob_lo     =  -32.e-6 -32.e-6 -32.e-6
geometry.prob_hi     =   32.e-6  32.e-6  32.e-6
amr.max_level = 0

#################################
############ NUMERICS ###########
#################################
warpx.verbose = 0
warpx.use_filter = 0
warpx.cfl = 1.
warpx.do_pml = 0

#algo.em_solver_medium = vacuum # vacuum/macroscopic
#algo.macroscopic_sigma_method = backwardeuler # laxwendroff or backwardeuler
#macroscopic.sigma = 0.0
#macroscopic.epsilon = 8.8541878128e-12
#macroscopic.mu = 1.25663706212e-06

particles.nspecies = 0

#################################
############ FIELDS #############
#################################

my_constants.pi = 3.14159265359
my_constants.L = 141.4213562373095e-6
my_constants.c = 299792458.
my_constants.wavelength = 64.e-6

warpx.E_ext_grid_init_style = parse_E_ext_grid_function
warpx.Ez_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Ex_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Ey_external_grid_function(x,y,z) = "x*x+y*y+z*z"

warpx.B_ext_grid_init_style = parse_B_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.By_external_grid_function(x,y,z) = "x*x+y*y+z*z"
warpx.Bz_external_grid_function(x,y,z) = "x*x+y*y+z*z"

warpx.M_ext_grid_init_style = constant
warpx.M_external_grid = 1. 2. 3.

#################################
############ DIAGNOSTICS #############
#################################

diagnostics.diags_names = diag1
diag1.period = 100
diag1.diag_type = Full

diag1.fields_to_plot = Ex Ey Ez Bx By Bz Mx_xface Mx_yface Mx_zface My_xface My_yface My_zface Mz_xface Mz_yface Mz_zface

diag1.plot_raw_fields = 1
`

**Review by RevathiJambunathan — APPROVED** [review]
Thank you! Looks great!

**Comment by ajnonaka** [comment]
I think I have addressed all the issues.  Take a final look and merge the PR if you like.

**Pull request merged**
